name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Cambia esto según tu rama principal
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up QEMU for cross-compilation
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.GHCR_PASSWORD }}
          password: ${{ secrets.GHCR_USERNAME }}

      - name: Build and push multi-platform image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: your_dockerhub_username/your_image_name:latest
          platforms: linux/amd64,linux/arm64 # Especifica las plataformas deseadas
