name: Build and Push Docker Image

on:
  push:
    branches:
      - main 
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up QEMU for cross-compilation
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}

      - name: Build and push multi-platform image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: r0mm31/cintalab:latest # Asegúrate de usar tu nombre de usuario y repositorio correctos
          platforms: linux/amd64,linux/arm64 # Especifica las plataformas deseadas
          cache-from: type=registry,ref=r0mm31/cintalab:cache # Usar caché desde el registro
          cache-to: type=registry,ref=r0mm31/cintalab:cache,mode=max # Guardar caché en el registro

      - name: Install Python and Requests Library
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Send Notification to Slack
        run: python notify_slack.py
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # Asegúrate de tener este secreto configurado

      - name: Custom message after push
        run: echo "La imagen de Alex y Roman se ha subido correctamente a Docker Hub."
